[package]
name = "ahe-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ahe-cli"
path = "src/main.rs"

[[bin]]
name = "bsgs-build"
path = "src/bin/bsgs_build.rs"

[[bin]]
name = "ahe-resnet-worker"
path = "src/bin/ahe_resnet_worker.rs"

[dependencies]
ahe-client.workspace = true
ahe-homomorphic.workspace = true
ahe-model-bundle.workspace = true
ahe-engine.workspace = true
ahe-codec.workspace = true
ahe-codec-ec.workspace = true
ahe-crypto-e2.workspace = true
num-bigint.workspace = true
anyhow.workspace = true
clap.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true